language: node_js
node_js:
  - "8.2.1"

install:
  - npm install -g newman

before_script:
  - node --version
  - npm --version
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - which newman
  - /usr/local/bin/newman -v

script:
  - /usr/local/bin/newman run collections/Postman Echo.postman_collection.json
