language: node_js
node_js:
    - "8.2.1"

install:
    - npm install -g newman

before_script:
    - node --version
    - npm --version
    - newman --version

script:
    - newman run collections/Postman Echo.postman_collection.json
