language: node_js
node_js:
  - "8.2.1"

install:
  - npm install -g newman

before_script:
  - node --version
  - npm --version
  - which newman
  - newman -v

script:
  - newman run collections/PostmanTests.postman_collection.json

